version: '3.8'

services:
  # База данных PostgreSQL
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=pizza
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db/pizza_dump.sql:/docker-entrypoint-initdb.d/pizza_dump.sql

  # Бэкенд ASP.NET Core API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pizza-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpireHours=${JWT_EXPIRE_HOURS}
    ports:
      - "5023:5023"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5023/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Фронтенд React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pizza-web
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 