FROM postgres:14-alpine

# Копируем SQL дамп в директорию инициализации
COPY docker/db/pizza_dump.sql /docker-entrypoint-initdb.d/

# Устанавливаем переменные окружения
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=123
ENV POSTGRES_DB=pizza

# Открываем порт PostgreSQL
EXPOSE 5432 