[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/health.html"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
ASPNETCORE_ENVIRONMENT = "Production"
PORT = "8080"
Jwt__Key = "supersecretkey_that_has_at_least_32_chars"
Jwt__Issuer = "PizzaWebApp"
Jwt__Audience = "PizzaWebAppUsers"
Jwt__ExpireHours = "2"

# Указываем, какой Dockerfile использовать для каждого сервиса
[services.backend]
dockerfilePath = "Dockerfile.backend"

[services.frontend]
dockerfilePath = "Dockerfile.frontend"