[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health-minimal.html"
healthcheckTimeout = 60
startCommand = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"