[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "3000"
VITE_API_URL = "https://backend-production-af78.up.railway.app/api"