[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_DATA_PROTECTION_PATH = "/app/DataProtection-Keys"
ASPNETCORE_DATA_PROTECTION_KEYSDIR = "/app/DataProtection-Keys"

# Указываем, какой Dockerfile использовать для каждого сервиса
[services.backend]
dockerfilePath = "Dockerfile.backend"

[services.frontend]
dockerfilePath = "Dockerfile.frontend"