[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "dist"
  environment = { VITE_API_URL = "http://localhost:5023/api" }

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
